name: "GitHub Actions for Dropbox"
description: "📦 Collection of GitHub Actions for Dropbox API. (Upload, Download .zip)"
branding:
  icon: upload-cloud
  color: blue

runs:
  using: "composite"
  steps:
    - name: Log
      uses: actions/github-script@v6
      with:
        script: |
          throw new Error(`See usage examples at: https://github.com/lgxm3z/gh-actions-dropbox`);
