name: "gh-actions-dropbox"
description: "📦 Github Actions for Dropbox API. (Upload, Download .zip)"
branding:
  icon: align-justify
  color: blue

runs:
  using: "composite"
  steps:
    - name: Log
      uses: actions/github-script@v6
      with:
        script: |
          throw new Error(`See usage examples at: https://github.com/lgxm3z/gh-actions-dropbox`);
